---
description: Microsoft Edge WebView2 コントロールを使用して Win32 アプリの web コンテンツをホストする
title: Win32 アプリ用 Microsoft Edge WebView2
author: MSEdgeTeam
ms.author: msedgedevrel
ms.date: 06/05/2020
ms.topic: reference
ms.prod: microsoft-edge
ms.technology: webview
keywords: IWebView2、IWebView2WebView、webview2、webview、win32 アプリ、win32、edge、ICoreWebView2、ICoreWebView2Controller、browser control、edge html
ms.openlocfilehash: 7f30bda4deb0811748c65880fcc49c21bc39a732
ms.sourcegitcommit: 8dca1c1367853e45a0a975bc89b1818adb117bd4
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 06/08/2020
ms.locfileid: "10697295"
---
# <span data-ttu-id="2f6c3-104">WebView2 クラス (EdgeNotFoundException クラス)</span><span class="sxs-lookup"><span data-stu-id="2f6c3-104">Microsoft.Web.WebView2.Core.EdgeNotFoundException class</span></span> 

> [!NOTE]
> <span data-ttu-id="2f6c3-105">この参照は、SDK バージョン0.9.515 後のリリースで変更される可能性があります。</span><span class="sxs-lookup"><span data-stu-id="2f6c3-105">This reference may be altered or unavailable for releases after SDK version 0.9.515.</span></span> <span data-ttu-id="2f6c3-106">最新 API リファレンスについては、 [WEBVIEW2 api リファレンス](../../../webview2-api-reference.md)を参照してください。</span><span class="sxs-lookup"><span data-stu-id="2f6c3-106">Please refer to [WebView2 API reference](../../../webview2-api-reference.md) for the latest API reference.</span></span>

<span data-ttu-id="2f6c3-107">名前空間: WebView2 () </span><span class="sxs-lookup"><span data-stu-id="2f6c3-107">Namespace: Microsoft.Web.WebView2.Core</span></span>\
<span data-ttu-id="2f6c3-108">"WebView2" アセンブリを実行します。</span><span class="sxs-lookup"><span data-stu-id="2f6c3-108">Assembly: Microsoft.Web.WebView2.Core.dll</span></span>

```
class Microsoft.Web.WebView2.Core.EdgeNotFoundException
  : public Exception
```

<span data-ttu-id="2f6c3-109">エッジのインストールが見つからない場合にスローされる例外。</span><span class="sxs-lookup"><span data-stu-id="2f6c3-109">The exception that is thrown when an Edge installation is missing.</span></span>

## <span data-ttu-id="2f6c3-110">まとめ</span><span class="sxs-lookup"><span data-stu-id="2f6c3-110">Summary</span></span>

 <span data-ttu-id="2f6c3-111">Members</span><span class="sxs-lookup"><span data-stu-id="2f6c3-111">Members</span></span>                        | <span data-ttu-id="2f6c3-112">説明</span><span class="sxs-lookup"><span data-stu-id="2f6c3-112">Descriptions</span></span>
--------------------------------|---------------------------------------------
[<span data-ttu-id="2f6c3-113">EdgeNotFoundException</span><span class="sxs-lookup"><span data-stu-id="2f6c3-113">EdgeNotFoundException</span></span>](#edgenotfoundexception) | <span data-ttu-id="2f6c3-114">EdgeNotFoundException クラスの新しいインスタンスを初期化します。</span><span class="sxs-lookup"><span data-stu-id="2f6c3-114">Initializes a new instance of the EdgeNotFoundException class.</span></span>
[<span data-ttu-id="2f6c3-115">EdgeNotFoundException</span><span class="sxs-lookup"><span data-stu-id="2f6c3-115">EdgeNotFoundException</span></span>](#edgenotfoundexception) | <span data-ttu-id="2f6c3-116">この例外の原因である内部例外への参照を使って、EdgeNotFoundException クラスの新しいインスタンスを初期化します。</span><span class="sxs-lookup"><span data-stu-id="2f6c3-116">Initializes a new instance of the EdgeNotFoundException class with a reference to the inner exception that is the cause of this exception.</span></span>
[<span data-ttu-id="2f6c3-117">EdgeNotFoundException</span><span class="sxs-lookup"><span data-stu-id="2f6c3-117">EdgeNotFoundException</span></span>](#edgenotfoundexception) | <span data-ttu-id="2f6c3-118">指定したエラーメッセージを使用して、EdgeNotFoundException クラスの新しいインスタンスを初期化します。</span><span class="sxs-lookup"><span data-stu-id="2f6c3-118">Initializes a new instance of the EdgeNotFoundException class with a specified error message.</span></span>
[<span data-ttu-id="2f6c3-119">EdgeNotFoundException</span><span class="sxs-lookup"><span data-stu-id="2f6c3-119">EdgeNotFoundException</span></span>](#edgenotfoundexception) | <span data-ttu-id="2f6c3-120">指定したエラーメッセージと、この例外の原因である内部例外への参照を指定して、EdgeNotFoundException クラスの新しいインスタンスを初期化します。</span><span class="sxs-lookup"><span data-stu-id="2f6c3-120">Initializes a new instance of the EdgeNotFoundException class with a specified error message and a reference to the inner exception that is the cause of this exception.</span></span>

## <span data-ttu-id="2f6c3-121">Members</span><span class="sxs-lookup"><span data-stu-id="2f6c3-121">Members</span></span>

#### <span data-ttu-id="2f6c3-122">EdgeNotFoundException</span><span class="sxs-lookup"><span data-stu-id="2f6c3-122">EdgeNotFoundException</span></span> 

<span data-ttu-id="2f6c3-123">EdgeNotFoundException クラスの新しいインスタンスを初期化します。</span><span class="sxs-lookup"><span data-stu-id="2f6c3-123">Initializes a new instance of the EdgeNotFoundException class.</span></span>

> <span data-ttu-id="2f6c3-124">パブリック[EdgeNotFoundException](#edgenotfoundexception)()</span><span class="sxs-lookup"><span data-stu-id="2f6c3-124">public [EdgeNotFoundException](#edgenotfoundexception)()</span></span>

#### <span data-ttu-id="2f6c3-125">EdgeNotFoundException</span><span class="sxs-lookup"><span data-stu-id="2f6c3-125">EdgeNotFoundException</span></span> 

<span data-ttu-id="2f6c3-126">この例外の原因である内部例外への参照を使って、EdgeNotFoundException クラスの新しいインスタンスを初期化します。</span><span class="sxs-lookup"><span data-stu-id="2f6c3-126">Initializes a new instance of the EdgeNotFoundException class with a reference to the inner exception that is the cause of this exception.</span></span>

> <span data-ttu-id="2f6c3-127">パブリック[EdgeNotFoundException](#edgenotfoundexception)(例外の内部)</span><span class="sxs-lookup"><span data-stu-id="2f6c3-127">public [EdgeNotFoundException](#edgenotfoundexception)(Exception inner)</span></span>

##### <span data-ttu-id="2f6c3-128">パラメーター</span><span class="sxs-lookup"><span data-stu-id="2f6c3-128">Parameters</span></span>
* `inner` <span data-ttu-id="2f6c3-129">現在の例外の原因である例外。</span><span class="sxs-lookup"><span data-stu-id="2f6c3-129">The exception that is the cause of the current exception.</span></span>

#### <span data-ttu-id="2f6c3-130">EdgeNotFoundException</span><span class="sxs-lookup"><span data-stu-id="2f6c3-130">EdgeNotFoundException</span></span> 

<span data-ttu-id="2f6c3-131">指定したエラーメッセージを使用して、EdgeNotFoundException クラスの新しいインスタンスを初期化します。</span><span class="sxs-lookup"><span data-stu-id="2f6c3-131">Initializes a new instance of the EdgeNotFoundException class with a specified error message.</span></span>

> <span data-ttu-id="2f6c3-132">パブリック[EdgeNotFoundException](#edgenotfoundexception)(文字列メッセージ)</span><span class="sxs-lookup"><span data-stu-id="2f6c3-132">public [EdgeNotFoundException](#edgenotfoundexception)(string message)</span></span>

##### <span data-ttu-id="2f6c3-133">パラメーター</span><span class="sxs-lookup"><span data-stu-id="2f6c3-133">Parameters</span></span>
* `message` <span data-ttu-id="2f6c3-134">例外の理由を説明するエラーメッセージ。</span><span class="sxs-lookup"><span data-stu-id="2f6c3-134">The error message that explains the reason for the exception.</span></span>

#### <span data-ttu-id="2f6c3-135">EdgeNotFoundException</span><span class="sxs-lookup"><span data-stu-id="2f6c3-135">EdgeNotFoundException</span></span> 

<span data-ttu-id="2f6c3-136">指定したエラーメッセージと、この例外の原因である内部例外への参照を指定して、EdgeNotFoundException クラスの新しいインスタンスを初期化します。</span><span class="sxs-lookup"><span data-stu-id="2f6c3-136">Initializes a new instance of the EdgeNotFoundException class with a specified error message and a reference to the inner exception that is the cause of this exception.</span></span>

> <span data-ttu-id="2f6c3-137">パブリック[EdgeNotFoundException](#edgenotfoundexception)(文字列メッセージ、例外の内部)</span><span class="sxs-lookup"><span data-stu-id="2f6c3-137">public [EdgeNotFoundException](#edgenotfoundexception)(string message, Exception inner)</span></span>

##### <span data-ttu-id="2f6c3-138">パラメーター</span><span class="sxs-lookup"><span data-stu-id="2f6c3-138">Parameters</span></span>
* `message` <span data-ttu-id="2f6c3-139">例外の理由を説明するエラーメッセージ。</span><span class="sxs-lookup"><span data-stu-id="2f6c3-139">The error message that explains the reason for the exception.</span></span> 

* `inner` <span data-ttu-id="2f6c3-140">現在の例外の原因である例外。</span><span class="sxs-lookup"><span data-stu-id="2f6c3-140">The exception that is the cause of the current exception.</span></span>

